keys:
  - &main age1fnjxdf7xgd8aczqxff6xn6wyfpa8dh3t3cxwk7e842rggz4nnges0nzdzk
  - &relic age1mtxt8atz3d92aee66xvutswkxe56fstwmpyhfjkvrnhzsmurq5ksgl6qk0
  - &blade age1ulf2vn6xz5gf6yc6axpctm5rptj8fnar5tcqrv5jh7udwg0ly9ps3kpexz
  - &hm age1sg5zxlwxha7expa7w3ehfq4y20qzv0sasu6mvdjqd469ym7csgnqctrfpn
  - &vega age1ueh30uzq36mzekugpjagyfwh8dam6lew9nqzsvwt07jmyuxzt9fsnrg6lt
creation_rules:
  - path_regex: secrets/hm.yaml$
    key_groups:
      - age:
        - *main
        - *hm
  - path_regex: secrets/relic.yaml$
    key_groups:
      - age:
        - *main
        - *relic
  - path_regex: secrets/blade.yaml$
    key_groups:
      - age:
        - *main
        - *blade
  - path_regex: secrets/vega.yaml$
    key_groups:
      - age:
        - *main
        - *vega
