# Copy this file into a conf.d/ directory such as
# ~/.config/pipewire/filter-chain.conf.d/
#
context.modules = [
    { name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {
            node.description = "Amplified mic source"
            media.name       = "Amplified mic source"
            filter.graph = {
                nodes = [
                    {
                        type = builtin
                        name = mic_gain
                        label = bq_highshelf
                        control = {
                            "Freq" = 0
                            "Q" = 1.0
                            "Gain" = +14.4
                        }
                    }
                ]
            }
            capture.props = {
                node.name = "effect_input.micgain"
                node.target = "alsa_input.usb-3142_FIFINE_K669_Microphone-00.mono-fallback"
                audio.rate = 48000
                node.passive = true
                audio.position = [ MONO ]
            }
            playback.props = {
                node.name = "effect_output.micgain"
                audio.position = [ MONO ]
                media.class = Audio/Source
            }
        }
    }
]
